---
- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: deployment

  # as newly created instances will not have group_vars/host_vars,
  # we will use include_vars

  roles:
    - ec2_create
