---
# to call this playbook:
# ansible-playbook --private-key ~/.ssh/tricky-key-pair-ireland.pem -e "env=staging instance_type=dbserver aws_region=eu-west-1 vpc_id=vpc-123456" -vvvv ec2_snapshot.yml
- hosts: "{{ instance_type }}"
  become: true
  gather_facts: true
  become_user: "{{ ec2_user }}"
  
  vars:
    aws_region: "{{ aws_region }}"

  tasks:
    - name: gather instance facts
      ec2_remote_facts:
      region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          "tag:env": "{{ env }}"
      register: ec2_info

    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids

    - set_fact:
         instance_ids: ec2_info.instance_ids

    - add_host: 
        hostname: "{{ item.public_ip }}" 
        groupname: ec2hosts
      with_items: ec2_info.instances

    - name: wait for instances to listen on port 22
      wait_for:
        state: started
        host: "{{ item.public_dns_name }}"
        port: 22
      with_items: ec2_info.instances

- hosts: ec2hosts
  gather_facts: true
  become: true
  become_user: "{{ ec2_user }}"
  
  tasks:
    - name: Debug inventory hosts
      debug: var=hostvars[inventory_hostname]
  
    - name: Create the snapshot
      ec2_snapshot:
        instance_id: "{{ hostvars[inventory_hostname]['ansible_ec2_instance-id'] }}"
        device_name: /dev/sda1
        description: snapshot of /data from "{{ hostvars[inventory_hostname]['ansible_ec2_instance-id'] }}" 



