---
# to call this playbook:
# ansible-playbook --private-key ~/.ssh/tricky-key-pair-ireland.pem -i dynamic_inventory/ -e "env=staging instance_type=dbserver aws_region=eu-west-1" -vvvv create_snapshot.yml
- name: gather instances ec2 facts
  hosts: localhost
  gather_facts: true

  roles:
    - ec2_snapshot_gather_facts

- name: take snapshot of instances 
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - ec2_snapshot_create
