---
# ansible-playbook --private-key ~/.ssh/tricky-key-pair-ireland.pem -i dynamic_inventory/ -e "env=staging server_type=dbserver aws_region=eu-west-1" -vvvv create_snapshot.yml

- name: "AWS | EBS | SNAPSHOT | Check environment name has been defined"
  fail: msg="You must specify the name of the environment e.g. staging"
  when: env is undefined

- name: "AWS | EBS | SNAPSHOT | Check server type name has been defined"
  fail: msg="You must specify the name of the server type e.g. dbserver"
  when: server_type is undefined

- name: "AWS | EBS | SNAPSHOT | Check aws region"
  fail: msg="You must specify a value for the aws region e.g. eu-west-1"
  when: aws_region is undefined